/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 🇧🇷 SamelCookies 🇧🇷 (https://sketchfab.com/ZamuelWarrior)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hound-backrooms-b835cbb0440942a0856da6cefd365d38
Title: Hound [Backrooms]
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    Object_8: THREE.SkinnedMesh
    Object_10: THREE.SkinnedMesh
    Object_12: THREE.SkinnedMesh
    Object_14: THREE.SkinnedMesh
    Object_15: THREE.SkinnedMesh
    Object_17: THREE.SkinnedMesh
    Object_18: THREE.SkinnedMesh
    Object_20: THREE.SkinnedMesh
    Object_22: THREE.SkinnedMesh
    Object_24: THREE.SkinnedMesh
    Object_26: THREE.SkinnedMesh
    Object_27: THREE.SkinnedMesh
    Object_28: THREE.SkinnedMesh
    GLTF_created_0_rootJoint: THREE.Bone
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/entity1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.273}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -0.658, -3.66]} rotation={[1.623, 0, 0]}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
              geometry={nodes.Object_7.geometry}
              material={materials['Material.002']}
              skeleton={nodes.Object_7.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_8.geometry}
              material={materials['Material.003']}
              skeleton={nodes.Object_8.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_10.geometry}
              material={materials['Material.001']}
              skeleton={nodes.Object_10.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_12.geometry}
              material={materials.Material}
              skeleton={nodes.Object_12.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_14.geometry}
              material={materials['Material.004']}
              skeleton={nodes.Object_14.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_15.geometry}
              material={materials['Material.007']}
              skeleton={nodes.Object_15.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_17.geometry}
              material={materials['Material.004']}
              skeleton={nodes.Object_17.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_18.geometry}
              material={materials['Material.007']}
              skeleton={nodes.Object_18.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_20.geometry}
              material={materials['Material.005']}
              skeleton={nodes.Object_20.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_22.geometry}
              material={materials['Material.001']}
              skeleton={nodes.Object_22.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_24.geometry}
              material={materials['Material.006']}
              skeleton={nodes.Object_24.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_26.geometry}
              material={materials.Material}
              skeleton={nodes.Object_26.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_27.geometry}
              material={materials.Material}
              skeleton={nodes.Object_27.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_28.geometry}
              material={materials.Material}
              skeleton={nodes.Object_28.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/entity1.glb')
