// client/src/models/Table.tsx
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 table.glb --types 
*/
import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

// read showGun from store to hide props after pickup (pure UI)
import useAppStore from "../zustand/store";

type GLTFResult = GLTF & {
  nodes: {
    Object_8002: THREE.Mesh;
    Object_6002: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_4004: THREE.Mesh;
    defaultMaterial: THREE.Mesh;
    defaultMaterial001: THREE.Mesh;
    Object_6003: THREE.Mesh;
    Object_8014: THREE.Mesh;
    Object_4005: THREE.Mesh;
    Object_4006: THREE.Mesh;
  };
  materials: {
    Table_Kitchen_A: THREE.MeshStandardMaterial;
    bullet_holder: THREE.MeshStandardMaterial;
    ammo_body: THREE.MeshStandardMaterial;
    ["material.005"]: THREE.MeshStandardMaterial;
    Material_001: THREE.MeshStandardMaterial;
    ["Material.039"]: THREE.MeshStandardMaterial;
    ["bullet_holder.001"]: THREE.MeshStandardMaterial;
    ["bullet_bottom.001"]: THREE.MeshStandardMaterial;
    ["material.006"]: THREE.MeshStandardMaterial;
    ["material.003"]: THREE.MeshStandardMaterial;
  };
};

export function Table(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/table.glb") as GLTFResult;
  const showGun = useAppStore((s) => s.showGun); // becomes true after pressing T

  return (
    <group {...props} dispose={null}>
      {/* Main table */}
      <mesh
        geometry={nodes.Object_8002.geometry}
        material={materials.Table_Kitchen_A}
        position={[-2.272, 0, -8.66]}
        rotation={[Math.PI, 0, Math.PI]}
      />

      {/* Hide the small props once the gun is picked up */}
      {!showGun && (
        <>
          <mesh
            geometry={nodes.Object_6002.geometry}
            material={materials.bullet_holder}
            position={[-1.897, 0.79, -8.356]}
            rotation={[0, -0.759, 0]}
            scale={[0.037, 0.011, 0.056]}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.ammo_body}
            position={[-1.595, 0.779, -8.488]}
            rotation={[0, -0.759, 0]}
            scale={[0.132, 0.093, 0.124]}
          />
          <mesh
            geometry={nodes.Object_4004.geometry}
            material={materials["material.005"]}
            position={[-1.818, 0.804, -8.439]}
            rotation={[Math.PI / 2, 0, 0.759]}
            scale={[0.151, 0.116, 0.106]}
          />
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.Material_001}
            position={[-1.789, 0.798, -8.619]}
            rotation={[-3.065, -0.739, 0]}
            scale={[0.081, 0.107, 0.086]}
          />
          <mesh
            geometry={nodes.defaultMaterial001.geometry}
            material={materials["Material.039"]}
            position={[-1.789, 0.8, -8.619]}
            rotation={[-3.065, -0.739, 0]}
            scale={[0.081, 0.107, 0.086]}
          />
          <mesh
            geometry={nodes.Object_6003.geometry}
            material={materials["bullet_holder.001"]}
            position={[-1.7, 0.782, -8.364]}
            rotation={[0, 0.455, 0]}
            scale={[0.037, 0.011, 0.056]}
          />
          <mesh
            geometry={nodes.Object_8014.geometry}
            material={materials["bullet_bottom.001"]}
            position={[-1.685, 0.783, -8.33]}
            rotation={[0, 0.455, 0]}
            scale={[0.132, 0.093, 0.124]}
          />
          <mesh
            geometry={nodes.Object_4005.geometry}
            material={materials["material.006"]}
            position={[-1.456, 0.8, -8.816]}
            rotation={[Math.PI / 2, 0, -0.455]}
            scale={[0.151, 0.116, 0.106]}
          />
          <mesh
            geometry={nodes.Object_4006.geometry}
            material={materials["material.003"]}
            position={[-1.401, 0.81, -8.241]}
            rotation={[Math.PI / 2, 0, 2.569]}
            scale={[0.151, 0.116, 0.106]}
          />
        </>
      )}
    </group>
  );
}

useGLTF.preload("/table.glb");
export default Table;
